apiVersion: v2
name: common
description: Function library for k8s-at-home charts
type: library
version: 4.5.7
kubeVersion: ">=1.16.0-0"
keywords:
  - k8s-at-home
  - common
home: https://github.com/k8s-at-home/library-charts/tree/main/stable/common
maintainers:
  - name: akarthik10
    email: akarthik10@users.noreply.github.com
